### ISSUE TITLE
[Improvement] Add Docker Variables for Fixed Server Adress, Username and Password etc.

### ISSUE THREAD

**Issue by kobayashi90** [rekkyrosso/ampcast#30]
It would be great if i could setup docker variables so i dont need to see the setup option even if other homeusers are using it.
Basically similar to what Aonsoku does. Example below

```
version: '3.8'
services:
  aonsoku:
    container_name: aonsoku
    image: ghcr.io/victoralvesf/aonsoku:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:7878:8080
    environment:
      - APP_USER=REDACTED
      - APP_PASSWORD=REDACTED
      - APP_AUTH_TYPE=token
      - SERVER_URL=REDACTED
      - HIDE_SERVER=true
```

Hope that this can be done.
